// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace RssFeeds.Models;

public partial class NewsFeed
{
    public int Id { get; set; }

    public int? NewsFeedUrlId { get; set; }

    public string? NewsFeedLink { get; set; }

    public string? NewsFeedExcert { get; set; }
}