// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace RssFeeds.Models;

public partial class NewsFeedContext : DbContext
{
    public NewsFeedContext(DbContextOptions<NewsFeedContext> options)
        : base(options)
    {
    }

    public virtual DbSet<NewsFeed> NewsFeeds { get; set; }

    public virtual DbSet<NewsFeedUrl> NewsFeedUrls { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}