// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace RssFeeds.Models;

public partial class NewsFeedUrl
{
    public int Id { get; set; }

    public string? NewsFeedUrl1 { get; set; }
}